# Generated by Django 2.0.1 on 2018-01-24 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenantprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='payment_method',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='payment_token',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='phone',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='profile_picture',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
