# Generated by Django 2.0.1 on 2018-01-28 03:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=50)),
                ('suburb', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('postcode', models.CharField(max_length=10)),
                ('bathrooms', models.IntegerField()),
                ('tenant_capacity', models.IntegerField()),
                ('description', models.TextField()),
                ('tag', models.CharField(max_length=50)),
                ('bedrooms', models.IntegerField()),
                ('price', models.FloatField()),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('date_sold', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property', to='property.PropertyStatus'),
        ),
    ]
